//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



// TODO: The 'ErrorPage' class has been commented out automatically due to usage of types that have no XAF for .NET equivalent.
//       Breaking Change https://supportcenter.devexpress.com/ticket/details/t1312589
//       Please review the class and implement necessary changes to ensure compatibility with XAF for .NET
// NOTE: Partial class part
//   - Type 'DevExpress.ExpressApp.Web.Templates.BaseXafPage' has no equivalent in XAF for .NET
//     BaseXafPage has no equivalent in XAF for .NET (loaded from removed-api.txt)
//   - Type 'DevExpress.ExpressApp.Web.TestScripts.TestScriptsManager' has no equivalent in XAF for .NET
//     TestScriptsManager has no equivalent in XAF for .NET (loaded from removed-api.txt)
//   - Type 'DevExpress.ExpressApp.Web.TestScripts.JSLabelTestControl' has no equivalent in XAF for .NET
//     JSLabelTestControl has no equivalent in XAF for .NET (loaded from removed-api.txt)
//   - Type 'DevExpress.ExpressApp.Web.TestScripts.TestControlType' has no equivalent in XAF for .NET
//     TestControlType has no equivalent in XAF for .NET (loaded from removed-api.txt)
//   - Type 'DevExpress.ExpressApp.Web.TestScripts.JSDefaultTestControl' has no equivalent in XAF for .NET
//     JSDefaultTestControl has no equivalent in XAF for .NET (loaded from removed-api.txt)
//   - Type 'DevExpress.ExpressApp.Web.ErrorInfo' has no equivalent in XAF for .NET
//     ErrorInfo has no equivalent in XAF for .NET (loaded from removed-api.txt)
//   - Type 'DevExpress.ExpressApp.Web.ErrorHandling' has no equivalent in XAF for .NET
//     ErrorHandling has no equivalent in XAF for .NET (loaded from removed-api.txt)
//   - Type 'DevExpress.ExpressApp.Web.SystemModule.RegisterThemeAssemblyController' has no equivalent in XAF for .NET
//     RegisterThemeAssemblyController has no equivalent in XAF for .NET (loaded from removed-api.txt)
// ========== COMMENTED OUT CLASS ==========
// public partial class ErrorPage {
//
//     /// <summary>
//     /// Head1 control.
//     /// </summary>
//     /// <remarks>
//     /// Auto-generated field.
//     /// To modify move field declaration from designer file to code-behind file.
//     /// </remarks>
//     protected global::System.Web.UI.HtmlControls.HtmlHead Head1;
//
//     /// <summary>
//     /// form1 control.
//     /// </summary>
//     /// <remarks>
//     /// Auto-generated field.
//     /// To modify move field declaration from designer file to code-behind file.
//     /// </remarks>
//     protected global::System.Web.UI.HtmlControls.HtmlForm form1;
//
//     /// <summary>
//     /// ApplicationTitle control.
//     /// </summary>
//     /// <remarks>
//     /// Auto-generated field.
//     /// To modify move field declaration from designer file to code-behind file.
//     /// </remarks>
//     protected global::System.Web.UI.WebControls.Literal ApplicationTitle;
//
//     /// <summary>
//     /// InfoMessagesPanel control.
//     /// </summary>
//     /// <remarks>
//     /// Auto-generated field.
//     /// To modify move field declaration from designer file to code-behind file.
//     /// </remarks>
//     protected global::System.Web.UI.WebControls.Literal InfoMessagesPanel;
//
//     /// <summary>
//     /// Table1 control.
//     /// </summary>
//     /// <remarks>
//     /// Auto-generated field.
//     /// To modify move field declaration from designer file to code-behind file.
//     /// </remarks>
//     protected global::System.Web.UI.WebControls.Table Table1;
//
//     /// <summary>
//     /// TableRow2 control.
//     /// </summary>
//     /// <remarks>
//     /// Auto-generated field.
//     /// To modify move field declaration from designer file to code-behind file.
//     /// </remarks>
//     protected global::System.Web.UI.WebControls.TableRow TableRow2;
//
//     /// <summary>
//     /// ViewSite control.
//     /// </summary>
//     /// <remarks>
//     /// Auto-generated field.
//     /// To modify move field declaration from designer file to code-behind file.
//     /// </remarks>
//     protected global::System.Web.UI.WebControls.TableCell ViewSite;
//
//     /// <summary>
//     /// ErrorTitleLiteral control.
//     /// </summary>
//     /// <remarks>
//     /// Auto-generated field.
//     /// To modify move field declaration from designer file to code-behind file.
//     /// </remarks>
//     protected global::System.Web.UI.WebControls.Literal ErrorTitleLiteral;
//
//     /// <summary>
//     /// ErrorPanel control.
//     /// </summary>
//     /// <remarks>
//     /// Auto-generated field.
//     /// To modify move field declaration from designer file to code-behind file.
//     /// </remarks>
//     protected global::System.Web.UI.WebControls.Panel ErrorPanel;
//
//     /// <summary>
//     /// ApologizeMessage control.
//     /// </summary>
//     /// <remarks>
//     /// Auto-generated field.
//     /// To modify move field declaration from designer file to code-behind file.
//     /// </remarks>
//     protected global::System.Web.UI.WebControls.PlaceHolder ApologizeMessage;
//
//     /// <summary>
//     /// HyperLink1 control.
//     /// </summary>
//     /// <remarks>
//     /// Auto-generated field.
//     /// To modify move field declaration from designer file to code-behind file.
//     /// </remarks>
//     protected global::System.Web.UI.WebControls.HyperLink HyperLink1;
//
//     /// <summary>
//     /// NavigateToStart control.
//     /// </summary>
//     /// <remarks>
//     /// Auto-generated field.
//     /// To modify move field declaration from designer file to code-behind file.
//     /// </remarks>
//     protected global::System.Web.UI.WebControls.LinkButton NavigateToStart;
//
//     /// <summary>
//     /// Details control.
//     /// </summary>
//     /// <remarks>
//     /// Auto-generated field.
//     /// To modify move field declaration from designer file to code-behind file.
//     /// </remarks>
//     protected global::System.Web.UI.WebControls.Panel Details;
//
//     /// <summary>
//     /// DetailsText control.
//     /// </summary>
//     /// <remarks>
//     /// Auto-generated field.
//     /// To modify move field declaration from designer file to code-behind file.
//     /// </remarks>
//     protected global::System.Web.UI.WebControls.Literal DetailsText;
//
//     /// <summary>
//     /// ReportForm control.
//     /// </summary>
//     /// <remarks>
//     /// Auto-generated field.
//     /// To modify move field declaration from designer file to code-behind file.
//     /// </remarks>
//     protected global::System.Web.UI.WebControls.Panel ReportForm;
//
//     /// <summary>
//     /// DescriptionTextBox control.
//     /// </summary>
//     /// <remarks>
//     /// Auto-generated field.
//     /// To modify move field declaration from designer file to code-behind file.
//     /// </remarks>
//     protected global::System.Web.UI.WebControls.TextBox DescriptionTextBox;
//
//     /// <summary>
//     /// ReportButton control.
//     /// </summary>
//     /// <remarks>
//     /// Auto-generated field.
//     /// To modify move field declaration from designer file to code-behind file.
//     /// </remarks>
//     protected global::System.Web.UI.WebControls.Button ReportButton;
// }
// ========================================

